# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/addressbook.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tutorial.Person" do
    optional :name, :string, 1
    optional :id, :int32, 2
    optional :email, :string, 3
    repeated :phones, :message, 4, "tutorial.Person.PhoneNumber"
    optional :last_updated, :message, 5, "google.protobuf.Timestamp"
  end
  add_message "tutorial.Person.PhoneNumber" do
    optional :number, :string, 1
    optional :type, :enum, 2, "tutorial.Person.PhoneType"
  end
  add_enum "tutorial.Person.PhoneType" do
    value :MOBILE, 0
    value :HOME, 1
    value :WORK, 2
  end
  add_message "tutorial.AddressBook" do
    repeated :people, :message, 1, "tutorial.Person"
  end
end

module Tutorial
  Person = Google::Protobuf::DescriptorPool.generated_pool.lookup("tutorial.Person").msgclass
  Person::PhoneNumber = Google::Protobuf::DescriptorPool.generated_pool.lookup("tutorial.Person.PhoneNumber").msgclass
  Person::PhoneType = Google::Protobuf::DescriptorPool.generated_pool.lookup("tutorial.Person.PhoneType").enummodule
  AddressBook = Google::Protobuf::DescriptorPool.generated_pool.lookup("tutorial.AddressBook").msgclass
end
